application:
  name: ersilia-hub

server:
  version: 0.0.27
  replicas: 1

  env:
    MAX_CONCURRENT_MODEL_INSTANCES: '100'
    WORK_REQUEST_WORKER_POD_READY_TIMEOUT: '900'
    ANON_WORK_REQUEST_CLEANUP_AGE: '10080' # time in minutes to keep ANON work requests
    ANON_WORK_REQUEST_CLEANUP_BATCH_SIZE: '1000' # batch size to clean anon work requests
    MAX_WORK_REQUEST_INPUT_SIZE: '1000' # max molecules/lines input
    MODEL_HUB_RECORDS_URL: 'https://www.ersilia.io/v1/datasource/airtable/5ce288d5-4600-42df-9d5f-8617b023a3e3/40117d92-6c86-49e2-94f1-ff4069ccbfd4/7811ffd5-cf42-4ace-85ea-5fc7490c47aa/3a852b80-9afe-4ae7-bad4-09a87afc7f8b/data'
    MODEL_HUB_DETAILS_BASE_URL: 'https://www.ersilia.io/v1/datasource/airtable/5ce288d5-4600-42df-9d5f-8617b023a3e3/0e97c68a-b15c-42bb-b34c-344cacfab08d/3e2b9c48-4162-40d0-8962-fb8852d85fbe/69ca2816-fba2-4d81-80a5-1e4f6a25f8dd/data'
    
    logs:
      ModelController: INFO
      ModelIntegrationController: TRACE
      K8sController: ERROR
      K8sProxyController: INFO
      WorkRequestController: INFO
      WorkRequestWorker: INFO
      JobSubmissionTask: TRACE
      S3IntegrationController: INFO
      AuthController: INFO
      NodeMonitor: ERROR
      ServerController: INFO
      FailedServerHandler: INFO
      ModelInstanceHandler: DEBUG
      JobSubmissionProcess: DEBUG
      InstanceMetricsController: ERROR

frontend:
  version: 0.0.17
  replicas: 1

