CREATE TABLE IF NOT EXISTS UserAuth (
    UserId text NOT NULL,
    PasswordHash text NOT NULL
);

ALTER TABLE UserAuth
  ADD CONSTRAINT USERAUTH_PKEY PRIMARY KEY (
    UserId
  );

ALTER TABLE UserAuth
  ADD CONSTRAINT USERAUTH_FK_USERID FOREIGN KEY (UserId)
  REFERENCES ErsiliaUser (Id);
