apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ b64enc $value }}
  {{- end }}