apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.application.name }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Values.application.name }}
    app.kubernetes.io/name: {{ .Values.application.name }}-server
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.serverRoleARN }}
automountServiceAccountToken: true
