apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.application.name }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Values.application.name }}
    app.kubernetes.io/name: {{ .Values.application.name }}-server
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - podtemplates
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.application.name }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Values.application.name }}
    app.kubernetes.io/name: {{ .Values.application.name }}-server
subjects:
  - kind: ServiceAccount
    name: {{ .Values.application.name }}-server
    namespace: {{ .Values.application.coreNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.application.name }}-server
