name: Build Server

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - feat/operations

    paths:
      - 'server/**'
      - '.github/workflows/build-server.yaml'

jobs:
  publish:
    name: 'Build and Publish Server'
    uses: './.github/workflows/docker-publish.yaml'
    with:
      image: 'ersilia-hub-server'
      version: '0.0.15' # TODO: move this to release-please later
      working_directory: 'server'
    secrets: inherit
